apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: mirror
spec:
  imageDigestMirrors:
    - mirrors:
        - harbor1.ocp.lab/quay.io
      source: quay.io
    - mirrors:
        - harbor1.ocp.lab/quay.io/openshift-release-dev/ocp-v4.0-art-dev
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    - mirrors:
        - harbor1.ocp.lab/quay.io/openshift-release-dev/ocp-release
      source: quay.io/openshift-release-dev/ocp-release
    - mirrors:
        - harbor1.ocp.lab/registry.redhat.io
        - harbor2.ocp.lab/registry.redhat.io
      source: registry.redhat.io
    - mirrors:
        - harbor1.ocp.lab/registry.connect.redhat.com
        - harbor2.ocp.lab/registry.connect.redhat.com
      source: registry.connect.redhat.com
    - mirrors:
        - harbor1.ocp.lab/registry.gitlab.com
        - harbor2.ocp.lab/registry.gitlab.com
      source: registry.gitlab.com
