apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  mirrorRegistryRef:
    name: custom-registries
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: "4.17"
    rootFSUrl: http://192.168.111.20:8080/rhcos-4.17.17-x86_64-live-rootfs.x86_64.img
    url: http://192.168.111.20:8080/rhcos-4.17.17-x86_64-live.x86_64.iso
    version: 417.94.202504142154-0
