apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/instance: advanced-cluster-management
spec:
  availabilityConfig: High
  enableClusterBackup: false
  ingress: {}
  separateCertificateManagement: false
